# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: control.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='control.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\rcontrol.proto\"\x15\n\x04Lane\x12\r\n\x05value\x18\x01 \x01(\x02\"*\n\x04Name\x12\r\n\x05value\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65stination\x18\x02 \x01(\t\"C\n\x10\x46uellDestination\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05\x66uell\x18\x02 \x01(\x05\x12\x12\n\npassengers\x18\x03 \x01(\x05\x32\xbf\x01\n\x07\x43ontrol\x12\x19\n\x07GetLane\x12\x05.Lane\x1a\x05.Lane\"\x00\x12\x1c\n\nGetOutLane\x12\x05.Lane\x1a\x05.Lane\"\x00\x12\"\n\x10SendAirplaneName\x12\x05.Name\x1a\x05.Lane\"\x00\x12!\n\x0fSendDestination\x12\x05.Name\x1a\x05.Name\"\x00\x12\x34\n\x16\x43heckPassengerAndFuell\x12\x11.FuellDestination\x1a\x05.Name\"\x00\x62\x06proto3')
)




_LANE = _descriptor.Descriptor(
  name='Lane',
  full_name='Lane',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='Lane.value', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=38,
)


_NAME = _descriptor.Descriptor(
  name='Name',
  full_name='Name',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='Name.value', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='destination', full_name='Name.destination', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=82,
)


_FUELLDESTINATION = _descriptor.Descriptor(
  name='FuellDestination',
  full_name='FuellDestination',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='FuellDestination.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fuell', full_name='FuellDestination.fuell', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='passengers', full_name='FuellDestination.passengers', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=84,
  serialized_end=151,
)

DESCRIPTOR.message_types_by_name['Lane'] = _LANE
DESCRIPTOR.message_types_by_name['Name'] = _NAME
DESCRIPTOR.message_types_by_name['FuellDestination'] = _FUELLDESTINATION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Lane = _reflection.GeneratedProtocolMessageType('Lane', (_message.Message,), dict(
  DESCRIPTOR = _LANE,
  __module__ = 'control_pb2'
  # @@protoc_insertion_point(class_scope:Lane)
  ))
_sym_db.RegisterMessage(Lane)

Name = _reflection.GeneratedProtocolMessageType('Name', (_message.Message,), dict(
  DESCRIPTOR = _NAME,
  __module__ = 'control_pb2'
  # @@protoc_insertion_point(class_scope:Name)
  ))
_sym_db.RegisterMessage(Name)

FuellDestination = _reflection.GeneratedProtocolMessageType('FuellDestination', (_message.Message,), dict(
  DESCRIPTOR = _FUELLDESTINATION,
  __module__ = 'control_pb2'
  # @@protoc_insertion_point(class_scope:FuellDestination)
  ))
_sym_db.RegisterMessage(FuellDestination)



_CONTROL = _descriptor.ServiceDescriptor(
  name='Control',
  full_name='Control',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=154,
  serialized_end=345,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetLane',
    full_name='Control.GetLane',
    index=0,
    containing_service=None,
    input_type=_LANE,
    output_type=_LANE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetOutLane',
    full_name='Control.GetOutLane',
    index=1,
    containing_service=None,
    input_type=_LANE,
    output_type=_LANE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SendAirplaneName',
    full_name='Control.SendAirplaneName',
    index=2,
    containing_service=None,
    input_type=_NAME,
    output_type=_LANE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SendDestination',
    full_name='Control.SendDestination',
    index=3,
    containing_service=None,
    input_type=_NAME,
    output_type=_NAME,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='CheckPassengerAndFuell',
    full_name='Control.CheckPassengerAndFuell',
    index=4,
    containing_service=None,
    input_type=_FUELLDESTINATION,
    output_type=_NAME,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CONTROL)

DESCRIPTOR.services_by_name['Control'] = _CONTROL

# @@protoc_insertion_point(module_scope)
