# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: control.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "Lane" do
    optional :value, :float, 1
  end
end

Lane = Google::Protobuf::DescriptorPool.generated_pool.lookup("Lane").msgclass
