# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: control.proto for package ''

require 'grpc'
require 'control_pb'

module Control
  class Service

    include GRPC::GenericService

    self.marshal_class_method = :encode
    self.unmarshal_class_method = :decode
    self.service_name = 'Control'

    rpc :GetLane, Lane, Lane
    rpc :GetOutLane, Lane, Lane
    rpc :SendAirplaneName, Name, Lane
    rpc :SendDestination, Name, Name
    rpc :CheckPassengerAndFuell, FuellDestination, Name
  end

  Stub = Service.rpc_stub_class
end
